// ===== Icon keys =====
// Defines the IconKey union used across the app. The actual icon images are
// PNGs in mobile/assets/icons/, rendered by PixelIcon.tsx. The pixel-art
// grid data below is kept as a reference/fallback from the web app but is
// no longer rendered anywhere.

export interface PixelIconDef {
  palette: Record<string, string>;
  rows: string[];
}

export type IconKey =
  | 'helmet'
  | 'jersey'
  | 'neckGuard'
  | 'shoulderPads'
  | 'elbowPads'
  | 'gloves'
  | 'pants'
  | 'shinGuards'
  | 'skates'
  | 'stick'
  | 'jock'
  | 'bag'
  | 'other';

// Shared ramps:
//  protective gear: n #7c93ad (light) / N #566f8c (base) / S #3d5266 (shade)
//  red gear:        r #f06a5a (light) / R #d23b34 (base) / N #8a2420 (shade)
const PROTECTIVE = { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', S: '#3d5266', B: '#3aa0e6' };

export const PIXEL_ICONS: Record<IconKey, PixelIconDef> = {
  helmet: {
    palette: { D: '#0e1b2b', H: '#f7f9fc', W: '#dde4ec', G: '#9aa5b5', C: '#39424f', k: '#11151c' },
    rows: [
      '................',
      '....DDDDDDDD....',
      '..DDHHHHHHHHDD..',
      '.DHHHWWWWWWWWGD.',
      '.DHHWWWWWWWWGGD.',
      '.DHWWWWWWWWWGGD.',
      '.DWWWWWWWWWWGGD.',
      '.DCCCCCCCCCCCCD.',
      '.DCkkCkkCkkCkkD.',
      '.DCkkCkkCkkCkkD.',
      '.DCCCCCCCCCCCCD.',
      '.DCkkCkkCkkCkkD.',
      '.DCkkCkkCkkCkkD.',
      '.DCCCCCCCCCCCCD.',
      '...DDDDDDDDDD...',
      '................',
    ],
  },
  jersey: {
    palette: { D: '#0e1b2b', R: '#d23b34', r: '#f06a5a', N: '#8a2420', W: '#f2f6fb' },
    rows: [
      '................',
      '....DDD..DDD....',
      '...DrRNNNNRrD...',
      '..DRrRNNNNRrRD..',
      '.DRrRRRRRRRRrRD.',
      '.DRrRRRRRRRRrRD.',
      '.DRrRRWWWWRRrRD.',
      '.DRrRRWWWWRRrRD.',
      '.DWWRRWWWWRRWWD.',
      '.DDDDRRRRRRDDDD.',
      '....DrRRRRND....',
      '....DrRRRRND....',
      '....DWWWWWWD....',
      '....DNNNNNND....',
      '....DDDDDDDD....',
      '................',
    ],
  },
  neckGuard: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '................',
      '..DD........DD..',
      '.DnND......DNSD.',
      '.DnND......DNSD.',
      '.DnNND....DNNSD.',
      '..DnNNNNNNNNSD..',
      '..DnNNNNNNNSSD..',
      '...DnNNNNNSSD...',
      '.....DnNNSD.....',
      '.....DnNNSD.....',
      '.....DnNNSD.....',
      '......DnSD......',
      '......DDDD......',
      '................',
      '................',
    ],
  },
  shoulderPads: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '..DDDD....DDDD..',
      '.DnnNND..DnnNND.',
      '.DnNNNDDDDNNNSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnBBBBBBBBBBSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '..DnNNNNNNNSSD..',
      '..DnNNNNNNNSSD..',
      '...DnNNNNNSSD...',
      '....DnNNNSSD....',
      '.....DDDDDD.....',
      '................',
      '................',
      '................',
    ],
  },
  elbowPads: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '..........DDDD..',
      '........DnNNSD..',
      '......DnNNNSD...',
      '.....DnNNNSD....',
      '....DnNNNSD.....',
      '...DDSNNSD......',
      '..DSSNNNSD......',
      '..DSSNNNSD......',
      '...DDSNNSD......',
      '....DnNNNSD.....',
      '.....DnNNNSD....',
      '......DnNNNSD...',
      '........DnNNSD..',
      '..........DDDD..',
      '................',
    ],
  },
  gloves: {
    palette: { D: '#0e1b2b', R: '#d23b34', r: '#f06a5a', N: '#8a2420', W: '#f2f6fb' },
    rows: [
      '................',
      '.....DDDDDD.....',
      '....DrrRRRRND...',
      '....DrrRRRRRND..',
      '....DrrRRRRRND..',
      '...DDrRRRRRND...',
      '...DRrRNRNRND...',
      '...DRrRNRNRND...',
      '...DRrRRRRRND...',
      '...DDRRRRRRND...',
      '..DNNNNNNNNNND..',
      '..DRrRRRRRRRND..',
      '..DRrWWRRRRRND..',
      '..DRRWWRRRRNND..',
      '..DDDDDDDDDDDD..',
      '................',
    ],
  },
  pants: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '..DDDDDDDDDDDD..',
      '..DBBBBBBBBBBD..',
      '..DNNNNNNNNNND..',
      '.DnnNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNDDNNNSSD.',
      '.DnNNND..DNNSD..',
      '.DnNNND..DNNSD..',
      '.DnNNND..DNNSD..',
      '.DnNNND..DNNSD..',
      '.DnNNND..DNNSD..',
      '.DDDDDD..DDDDDD.',
      '................',
      '................',
    ],
  },
  shinGuards: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '.....DDDDDD.....',
      '...DDnnNNSSDD...',
      '..DnnNNNNNNSSSD.',
      '..DnNNNNNNNNSSD.',
      '..DnNNNNNNNNSSD.',
      '..DSSSSSSSSSSSD.',
      '..DnNNnnNNNSSD..',
      '..DnNNnnNNNSSD..',
      '..DnNNnnNNNSSD..',
      '..DnNNnnNNNSSD..',
      '..DSSSSSSSSSSSD.',
      '...DnNNNNNNSSD..',
      '....DnNNNNSSD...',
      '....DDDDDDDD....',
      '................',
    ],
  },
  skates: {
    palette: { D: '#0e1b2b', B: '#2f7fc4', b: '#7cc0f2', s: '#1d5a8f', W: '#f2f6fb', k: '#1a1a1a', Z: '#dfe7f0', z: '#9aa5b5' },
    rows: [
      '................',
      '...DDDDDDDD.....',
      '..DBbBBBBBsD....',
      '..DBbBBBBBsD....',
      '..DBbWBWBWsD....',
      '..DBBWBWBWBsD...',
      '..DBBBBBBBBBsD..',
      '..DBBBBBBBBssD..',
      '..DkkkkkkkkkkD..',
      '...DD......DD...',
      '.DZZZZZZZZZZZZD.',
      '.DzzzzzzzzzzzzD.',
      '.DDDDDDDDDDDDDD.',
      '................',
      '................',
      '................',
    ],
  },
  stick: {
    palette: { D: '#0e1b2b', T: '#d9a55a', t: '#b9863c', K: '#1a1a1a' },
    rows: [
      '................',
      '............DDD.',
      '...........DTtD.',
      '..........DTtD..',
      '.........DTtD...',
      '........DTtD....',
      '.......DTtD.....',
      '......DTtD......',
      '.....DTtD.......',
      '....DTtD........',
      '...DTtD.........',
      '..DKKKtD........',
      '.DKKKKKKD.......',
      '.DDDDDDDD.......',
      '................',
      '................',
    ],
  },
  jock: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '..DDDDDDDDDDDD..',
      '..DnnNNNNNNSSD..',
      '....DnnNNSSD....',
      '...DnnNNNNSSD...',
      '...DnNNNNNSSD...',
      '...DnNNNNNSSD...',
      '...DnNNNNNSSD...',
      '....DnNNNNSSD...',
      '....DnNNNNSSD...',
      '.....DnNNSD.....',
      '.....DnNNSD.....',
      '......DnSD......',
      '......DDDD......',
      '................',
      '................',
    ],
  },
  bag: {
    palette: { ...PROTECTIVE },
    rows: [
      '................',
      '.....DDDDDD.....',
      '....DD....DD....',
      '..DDDDDDDDDDDD..',
      '..DnnNNDDNNSSD..',
      '.DnnNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNBBBBBBBNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DnNNNNNNNNNSSD.',
      '.DNSSSSSSSSSSSD.',
      '..DDDDDDDDDDDD..',
      '................',
      '................',
    ],
  },
  other: {
    palette: { D: '#0e1b2b', k: '#2b2f36', K: '#15171b', L: '#5a6472' },
    rows: [
      '................',
      '................',
      '................',
      '....DDDDDDDD....',
      '..DDkkkkkkkkDD..',
      '.DkLLkkkkkkkkkD.',
      '.DkLLLkkkkkkkkD.',
      '.DkkkkkkkkkkkkD.',
      '.DkKKKKKKKKKKKD.',
      '.DKKKKKKKKKKKKD.',
      '.DKKKKKKKKKKKKD.',
      '..DKKKKKKKKKKD..',
      '...DDDDDDDDDD...',
      '................',
      '................',
      '................',
    ],
  },
};
