// ===== Pixel icons (16-bit SNES style) =====
// Ported from the original web app's ikoner.js.
// Each icon is a grid of pixels: one letter = one color from the palette,
// "." = transparent. To change an icon, just redraw the grid below.

export interface PixelIconDef {
  palette: Record<string, string>;
  rows: string[];
}

export type IconKey =
  | 'helmet'
  | 'jersey'
  | 'neckGuard'
  | 'shoulderPads'
  | 'elbowPads'
  | 'gloves'
  | 'pants'
  | 'shinGuards'
  | 'skates'
  | 'stick'
  | 'jock'
  | 'bag'
  | 'other';

export const PIXEL_ICONS: Record<IconKey, PixelIconDef> = {
  helmet: {
    palette: { D: '#0e1b2b', L: '#f7f9fc', W: '#dde4ec', G: '#b9c2cf', g: '#8d97a6', C: '#3a4250', K: '#11151c' },
    rows: [
      '.......DLLLLD.......',
      '.....DLLLLLLLLD.....',
      '...DLLLLLLLLLLLLD...',
      '..DWWWWWWWWWWWWWWD..',
      '.DWWWWWWWWWWWWWWWWD.',
      '.DWDWDWDWWWWDWDWDWD.',
      '.DGGGGGGGGGGGGGGGGD.',
      '.DGGGGGGGGGGGGGGGGD.',
      '..DggggggggggggggD..',
      '...DggggggggggggD...',
      '..DCCCCCCCCCCCCCCD..',
      '..DC..C..C..C..C.D..',
      '..DC..C..C..C..C.D..',
      '..DCCCCCCCCCCCCCCD..',
      '..DC..C..C..C..C.D..',
      '..DC..C..C..C..C.D..',
      '..DCCCCCCCCCCCCCCD..',
      '..DC..C..C..C..C.D..',
      '..DC..C..C..C..C.D..',
      '..DCCCCCCCCCCCCCCD..',
      '....DKKKKKKKKKKD....',
      '......DKKKKKKD......',
      '....................',
    ],
  },
  jersey: {
    palette: { D: '#5a1414', J: '#d23b34', j: '#f06a5a', W: '#f2f6fb', N: '#8a2420' },
    rows: [
      '....DJJD..DJJD....',
      '...DJjjjJJjjjJD...',
      '..DJjjjWWWWjjjJD..',
      '.DJJWWWWWWWWWWJJD.',
      '.DJJJJJJJJJJJJJJD.',
      '.DJJJJJWWWWJJJJJD.',
      '.DJJJJJWWWWJJJJJD.',
      '.DJJJJJWWWWJJJJJD.',
      '.DjjjjjjjjjjjjjjD.',
      '.DNNNNNNNNNNNNNND.',
      '.DWWWWWWWWWWWWWWD.',
      '.DDDDDDDDDDDDDDDD.',
      '....DDDDDDDDDD....',
      '..................',
    ],
  },
  shoulderPads: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', B: '#3aa0e6' },
    rows: [
      '....DnnD..DnnD....',
      '..DNnnND.DNnnND...',
      '..DNnnnNNNNnnnND..',
      '..DNnBBBBBBBBnND..',
      '..DNnnnnnnnnnnND..',
      '..DNnnnnnnnnnnND..',
      '...DNnnnnnnnnND...',
      '...DNnnnnnnnnND...',
      '....DNnnnnnnND....',
      '.....DNnnnnND.....',
      '......DDDDDD......',
      '..................',
    ],
  },
  elbowPads: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', S: '#c2ccd8' },
    rows: [
      '.....DNNNNNND.....',
      '..DNnnnnnnnnnD....',
      '..DNnnnnnnnnnnND..',
      '..DNnnnnnnnnnnNDSS',
      '.DNnnnnnnnnnnNDSsS',
      '..DNnnnnnnnnnnNDSS',
      '..DNnnnnnnnnnnND..',
      '..DNnnnnnnnnnnNDSS',
      '.DNnnnnnnnnnnNDSsS',
      '....DNnnnnnnnnNDSS',
      '....DNnnnnnnND....',
      '.....DNNNNNND.....',
      '..................',
    ],
  },
  gloves: {
    palette: { D: '#3a0f0f', R: '#e23b3b', r: '#f47a6a', W: '#f2f6fb', N: '#8c2424' },
    rows: [
      '..D.D.D.D.D.......',
      '.DRDRDRDRD........',
      '.DrDrDrDrD........',
      '.DRRRRRRRRD.......',
      '.DRrrrrrrRD.......',
      'DDRrrrrrrRD.......',
      'DRRRrrrrrRD.......',
      'DRrRRRRRRRD.......',
      '.DRRRRRRRRD.......',
      '.DNNNNNNNND.......',
      '.DWWWWWWWWD.......',
      '.DWWWWWWWWD.......',
      '..DDDDDDDD........',
      '..................',
    ],
  },
  pants: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', B: '#3aa0e6' },
    rows: [
      '.DDDDDDDDDDDDDDDD.',
      '.DNNNNNNNNNNNNNND.',
      '.DBBBBBBBBBBBBBBD.',
      '.DnnnnnnnnnnnnnnD.',
      '.DnnnnnnnnnnnnnnD.',
      '.DnnnnnnnnnnnnnnD.',
      '.Dnnnnn....nnnnnD.',
      '.Dnnnn......nnnnD.',
      '.Dnnn........nnnD.',
      '.Dnn..........nnD.',
      '..DD..........DD..',
      '..................',
    ],
  },
  shinGuards: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', S: '#d3deeb' },
    rows: [
      '......DSSSSD......',
      '....DSSSSSSSSD....',
      '....DSnnnnnnSD....',
      '....DSSSSSSSSD....',
      '....DnnnnnnnnD....',
      '...DNNNNNNNNNND...',
      '..DnnSSnnnnSSnnD..',
      '..DnnSSnnnnSSnnD..',
      '..DnnSSnnnnSSnnD..',
      '..DnnnnnnnnnnnnD..',
      '..DnnnnnnnnnnnnD..',
      '...DnnnnnnnnnnD...',
      '....DnnnnnnnnD....',
      '.....DDDDDDDD.....',
      '..................',
    ],
  },
  skates: {
    palette: { D: '#0e1b2b', B: '#2f7fc4', b: '#7cc0f2', W: '#f2f6fb', Z: '#dfe7f0', k: '#1a1a1a' },
    rows: [
      '...DDDDDDDD.......',
      '..DBBBBBBD........',
      '..DBWbWBBD........',
      '..DBWbWBBDD.......',
      '..DBWbWBBBBD......',
      '..DBBBBBBBBBBD....',
      '..DBBBBBBBBBBD....',
      '..DkkkkkkkkkkD....',
      '...DDDDDDDDDDD....',
      '....D.............',
      '..ZZZZZZZZZZZZZ...',
      '...DZZZZZZZZZD....',
      '..................',
    ],
  },
  stick: {
    palette: { D: '#0e1b2b', T: '#d9a55a', t: '#b9863c', K: '#1a1a1a', W: '#f2f6fb' },
    rows: [
      '.............DD...',
      '............DTtD..',
      '...........DWtD...',
      '..........DTtD....',
      '.........DWtD.....',
      '........DTtD......',
      '.......DWtD.......',
      '......DTtD........',
      '.....DTtD.........',
      '...DKKtD..........',
      '..DKKKKD..........',
      '.DKKKKKKD.........',
      '.DDDDDDDD.........',
      '..................',
    ],
  },
  jock: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad' },
    rows: [
      '..................',
      '..DDDDDDDDDDDD....',
      '..DNNNNNNNNNND....',
      '..DnnnnnnnnnnD....',
      '..DnnnnnnnnnnD....',
      '...DnnnnnnnnD.....',
      '...DnnnnnnnnD.....',
      '....DnnnnnnD......',
      '.....DnnnnD.......',
      '......DnnD........',
      '.......DD.........',
      '..................',
    ],
  },
  bag: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad', R: '#e23b3b' },
    rows: [
      '..................',
      '....DDDDDDDD......',
      '...DD......DD.....',
      '..DDDDDDDDDDDD....',
      '.DnnnnnnnnnnnnD...',
      '.DnnnnnnnnnnnnD...',
      '.DRRRRRRRRRRRRD...',
      '.DnnnnnnnnnnnnD...',
      '.DnnnnnnnnnnnnD...',
      '..NNNNNNNNNNNN....',
      '..................',
    ],
  },
  neckGuard: {
    palette: { D: '#0e1b2b', N: '#566f8c', n: '#7c93ad' },
    rows: [
      '..................',
      '....DDDDDDDDDD....',
      '...DNNNNNNNNNND...',
      '..DnnnnnnnnnnnnD..',
      '..DnDDDDDDDDDDnD..',
      '..DnD........DnD..',
      '..DnD........DnD..',
      '...DnD......DnD...',
      '...DnDDDDDDDnD....',
      '.....DnnnnnnD.....',
      '......DDDDDD......',
      '..................',
    ],
  },
  other: {
    palette: { D: '#0e1b2b', T: '#d9a55a', t: '#b9863c' },
    rows: [
      '......DDDDDD......',
      '....DTttttttTD....',
      '...DttttttttttD...',
      '..DttttttttttttD..',
      '..DttttttttttttD..',
      '..DttttttttttttD..',
      '..DttttttttttttD..',
      '..DttttttttttttD..',
      '...DttttttttttD...',
      '....DTttttttTD....',
      '......DDDDDD......',
      '..................',
    ],
  },
};
